### PR TITLE
adds apollo client and provider

### PR DESCRIPTION
**Pull request by a-7-s**
Not sure what our apollo url is in this case but I think this is what we need to make `useQuery` work in these cases.

### CODE REVIEW

**Review by dav1do — APPROVED** [review]

**Comment by a-7-s** [comment]
Ah nevermind, I see we have a client in a context right now but also need to pass it to the provider.

**Comment by a-7-s** [comment]
still see `Uncaught Error: invariant expected app router to be mounted` which I'm not sure why, but I think some components return undefined and aren't valid react children.

Also see weird warnings `- warn ./node_modules/ethers/node_modules/ws/lib/buffer-util.js` related to ws for some reason.

**Comment by a-7-s** [comment]
> still see `Uncaught Error: invariant expected app router to be mounted` which I'm not sure why, but I think some components return undefined and aren't valid react children.
> 
> Also see weird warnings `- warn ./node_modules/ethers/node_modules/ws/lib/buffer-util.js` related to ws for some reason.

[f63dc84](https://github.com/dbcfd/ai-repo/pull/17/commits/f63dc846e37a7dade6c1c963e71049630dac8b77)

**Comment by a-7-s** [comment]
[7656640](https://github.com/dbcfd/ai-repo/pull/17/commits/76566409ce8b08b120db16465f93959d8eb7b177) removes react router because we already get next router with next. I thought the `expected app router to be mounted`invariant error was going to be related to that but it's not, still not sure there.

**Comment by a-7-s** [comment]
ok got the invariant error fixed, need to only wrap children with the context providers.

[02cc54c](https://github.com/dbcfd/ai-repo/pull/17/commits/02cc54cc9ec828d644b3963d3be60fa07c28a587)

**Pull request merged**
